theme: jekyll-theme-minimal
title: Asphyxia
logo: /img/core-logo.png
description: |
  <ul class="downloads">
    <li><a href="#">Download <strong>CORE</strong></a></li>
      <li><a href="#">Setup <strong>Guides</strong></a></li>
    <li><a href="typedoc">Developer <strong>Docs</strong></a></li>
  </ul>
include:
  - typedoc
  - _.html
